# Generated by Django 4.1.2 on 2023-11-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_diaryentry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(default='Goal', max_length=100),
        ),
    ]
