# Generated by Django 4.2.5 on 2023-10-21 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_diaryentry_goal_user_userprofile_delete_profile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryentry',
            options={'verbose_name_plural': 'Diary entries'},
        ),
    ]
