# Generated by Django 4.1.2 on 2023-11-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_goal_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
