# Generated by Django 4.1.2 on 2023-11-23 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_diaryentry_date_alter_goal_start_date'),
        ('users', '0004_reminder'),
    ]

    operations = [
    ]
