# Generated by Django 4.2.5 on 2023-10-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='calories_burned',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='title',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='type',
        ),
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(default='Default Workout Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FavoriteWorkout',
        ),
    ]
