# Generated by Django 4.2.5 on 2023-10-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_remove_workout_calories_burned_remove_workout_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='workout',
            name='reps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='sets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
