# Generated by Django 4.2.5 on 2023-10-25 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_remove_set_exercise_remove_set_workout_workout_reps_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='name',
            new_name='name1',
        ),
    ]
