# Generated by Django 4.2.5 on 2023-10-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0011_rename_name_workout_name1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='name1',
        ),
        migrations.AddField(
            model_name='workout',
            name='WorkoutDay',
            field=models.CharField(default='', max_length=255),
        ),
    ]
