# Generated by Django 4.2.5 on 2023-10-30 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0016_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='reps',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='workout',
            name='sets',
            field=models.PositiveIntegerField(),
        ),
    ]
