# Generated by Django 4.1.2 on 2023-10-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0021_customworkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customworkout',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
