# Generated by Django 4.1.2 on 2023-11-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0023_remove_workout_exercise_remove_workout_reps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customworkout',
            name='category',
        ),
        migrations.AddField(
            model_name='workout',
            name='day',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
