# Generated by Django 4.1.2 on 2023-11-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0024_remove_customworkout_category_workout_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='day',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
