# Generated by Django 4.1.2 on 2023-11-07 00:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0029_remove_workout_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
