# Generated by Django 4.1.2 on 2023-11-07 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0030_workout_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='date_posted',
        ),
    ]
