# Generated by Django 4.1.2 on 2023-11-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0031_remove_workout_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='day',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
