# Generated by Django 4.1.2 on 2023-12-02 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0034_remove_customworkout_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomWorkout',
        ),
    ]
